spring:
  application:
    name: skopjepulse
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/pulse
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
