spring:
  application:
    name: pulse
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/testpulse
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
